runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /
  static_dir: static

# Sign up to openweathermap.org and obtain a new API key, then replace the value of WEATHER_API_KEY.
env_variables:
  WEATHER_API_KEY: 'get your own!'